steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$Project_Id/line-gpt-bot', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$Project_Id/line-gpt-bot']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
images:
  - 'gcr.io/$Project_Id/line-gpt-bot'
